# This workflow adds the community approval label ("lgtm") to pull requests. It
# does *not* indicate maintainer approval. This a way to visually highlight that
# someone in the world thinks the pull request is ready for further review. This
# event is triggered by a pull request approval, or simply a comment that
# contains the text "lgtm".
# Webhook events: Issue comments, Pull request reviews
name: Community approval
on:
  repository_dispatch:
    # From: issue_comment, pull_request_review
    types: [opened, created, edited, submitted]

jobs:
  lgtm-comment:
    # Check the comment. contains() is case-insensitive.
    if: >-
      ${{ github.actor == 'tfdocsbot' &&
          contains(github.event.client_payload.comment.body, 'LGTM') }}
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.client_payload.comment.issue_url }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          "${ISSUE_URL}/labels" \
          --data '{"labels":["lgtm"]}'

  review-approval:
    # Check the pull request review.
    if: >-
      ${{ github.actor == 'tfdocsbot' &&
          contains(github.event.client_payload.review.state, 'approved') }}
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.client_payload.pull_request.issue_url }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          "${ISSUE_URL}/labels" \
          --data '{"labels":["lgtm"]}'

  review-vendor-debug:
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      env:
        TEST_A: ${{ github.actor }}
        TEST_B: ${{ github.event.client_payload.pull_request.user.login }}
        TEST_C: ${{ github.event.client_payload.pull_request.body }}
        TEST_D: ${{ github.event.client_payload.action }}
      run: |
        echo "here"
        echo "actor: $TEST_A, login: $TEST_B, event: $TEST_D"
        echo "body: $TEST_C"

  review-vendor:
    # Label pull requests that have already been reviewed by vendors in GitLocalize.
    # gitlocalize-app[bot]
    if: >-
      ${{ github.actor == 'tfdocsbot' &&
          github.event.client_payload.action == 'opened' &&
          github.event.client_payload.pull_request.user.login == 'lamberta' &&
          contains(github.event.client_payload.pull_request.body, 'Translated by Alconost') }}
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.client_payload.pull_request.issue_url }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          "${ISSUE_URL}/labels" \
          --data '{"labels":["lgtm-vendor"]}'
