name: Continuous Integration
on: push

jobs:
  format_notebooks:
    name: Format notebooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout user/docs-l10n
      uses: actions/checkout@v2
      with:
        path: docs-l10n
    - name: Checkout tensorflow/docs
      uses: actions/checkout@v2
      with:
        repository: tensorflow/docs
        path: docs
    - uses: actions/setup-python@v1
    - name: Set up environment
      run: |
        pip install --upgrade absl-py
        cd ./docs-l10n && git fetch origin master:master
    - name: nbfmt
      run: |
        cd ./docs-l10n
        git branch
        echo "On branch: $(git rev-parse --abbrev-ref HEAD)"
        echo "---"
        NOTEBOOKS_CHANGED="$(git diff --name-only master | grep '\.ipynb$')"
        echo "--> $NOTEBOOKS_CHANGED"
        python ../docs/tools/nbfmt.py --ignore_warn $NOTEBOOKS_CHANGED
