name: Continuous Integration
on: push

jobs:
  nbfmt:
    name: nbfmt
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tensorflow/docs-l10n
      uses: actions/checkout@v2
      with:
        path: docs-l10n
    - name: Checkout tensorflow/docs
      uses: actions/checkout@v2
      with:
        repository: tensorflow/docs
        path: docs
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install --upgrade absl-py
#    - name: Format notebook
#      run: ./tools/nbfmt_pr.sh
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Show environment
      run: |
        pwd
        ls -al
