name: Continuous Integration
on: push

jobs:
  format_notebooks:
    name: Format notebooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout user/docs-l10n
      uses: actions/checkout@v2
      with:
        path: docs-l10n
    - name: Checkout tensorflow/docs
      uses: actions/checkout@v2
      with:
        repository: tensorflow/docs
        path: docs
    - uses: actions/setup-python@v1
    - name: Set up environment
      run: |
        pip install --upgrade absl-py
        cd ./docs-l10n && git fetch origin master:master
        git config --global user.email "tfdocsbot+no-reply@gmail.com"
        git config --global user.name "TF DocsBot"
    - name: nbfmt
      run: |
        cd ./docs-l10n
        NOTEBOOKS_CHANGED="$(git diff --name-only master | grep '\.ipynb$')"
        echo "Run nbfmt.py on updated notebooks:"
        python ../docs/tools/nbfmt.py --ignore_warn $NOTEBOOKS_CHANGED
        git add $NOTEBOOKS_CHANGED
        git commit -m "CI: nbfmt"
        git push
