name: Comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
    - name: Add community approval label
      if: "contains(github.event.comment.body, 'LGTM')"
      env:
        URL: "${{ github.event.issue.labels_url }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        echo ">>${URL}<<"
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          $URL \
          --data '{"labels":["lgtm"]}'
